kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: bazarr-configs-pvc
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazarr
  labels:
    app: bazarr
  annotations:
    keel.sh/policy: "force"
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@every 168h"
    keel.sh/approvals: "0"
    keel.sh/match-tag: "true"
spec:
  replicas: 1
  strategy:
    type: Recreate  
  selector:
    matchLabels:
      app: bazarr
  template:
    metadata:
      labels:
        app: bazarr
    spec:
      nodeSelector:
        topology.kubernetes.io/zone: home-1
      volumes:
        - name: media-nfs
          nfs:
            server: 10.73.95.84
            path: /mnt/tank/media
        - name: bazarr-configs
          persistentVolumeClaim:
            claimName: bazarr-configs-pvc
      containers:
        - name: bazarr
          image: lscr.io/linuxserver/bazarr:latest
          imagePullPolicy: "IfNotPresent"
          resources:
            requests:
              memory: 512Mi
            limits:
              memory: 512Mi
          volumeMounts:
            - name: media-nfs
              mountPath: /media
            - name: bazarr-configs
              mountPath: /config
---
apiVersion: v1
kind: Service
metadata:
  name: bazarr
spec:
  selector:
    app: bazarr
  ports:
    - protocol: TCP
      port: 6767
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bazarr-private
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - bazarr.keen.land
      secretName: keenland-bazarr-ingress-cert
  rules:
    - host: bazarr.keen.land
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bazarr
                port:
                  number: 6767
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: bazarr
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       bazarr
  updatePolicy:
    updateMode: "Off"
