kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prowlarr-configs-pvc
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  labels:
    app: prowlarr
  annotations:
    keel.sh/policy: "force"
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@every 24h"
    keel.sh/approvals: "0"
    keel.sh/match-tag: "true"
spec:
  replicas: 1
  strategy:
    type: Recreate  
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      nodeSelector:
        topology.kubernetes.io/zone: home-1
      volumes:
        - name: media-nfs
          nfs:
            server: 10.73.95.84
            path: /mnt/tank/media
        - name: prowlarr-configs
          persistentVolumeClaim:
            claimName: prowlarr-configs-pvc
      containers:
        - name: prowlarr
          image: lscr.io/linuxserver/prowlarr:latest
          imagePullPolicy: "IfNotPresent"
          resources:
            requests:
              memory: 256Mi
            limits:
              memory: 256Mi
          volumeMounts:
            - name: media-nfs
              mountPath: /media
            - name: prowlarr-configs
              mountPath: /config
---
apiVersion: v1
kind: Service
metadata:
  name: prowlarr
spec:
  selector:
    app: prowlarr
  ports:
    - protocol: TCP
      port: 9696
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prowlarr-private
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - prowlarr.keen.land
      secretName: keenland-prowlarr-ingress-cert
  rules:
    - host: prowlarr.keen.land
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prowlarr
                port:
                  number: 9696
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: prowlarr
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       prowlarr
  updatePolicy:
    updateMode: "Off"
