---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sabnzbd-private
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - sabnzbd.keen.land
      secretName: keenland-sabnzbd-ingress-cert
  rules:
    - host: sabnzbd.keen.land
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sabnzbd
                port:
                  number: 8080
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: sabnzbd
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       sabnzbd
  updatePolicy:
    updateMode: "Off"
