apiVersion: apps/v1
kind: Deployment
metadata:
  name: ezshare-sync
  labels:
    app: ezshare-sync
  annotations:
    keel.sh/policy: "force"
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@every 1m"
    keel.sh/approvals: "0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ezshare-sync
  template:
    metadata:
      labels:
        app: ezshare-sync
    spec:
      volumes:
        - name: cpap-nfs
          nfs:
            server: 10.73.95.84
            path: /mnt/tank/cpap/pete
      imagePullSecrets:
        - name: ghcr.io
      containers:
        - name: ezshare-sync
          image: ghcr.io/keenfamily-us/infra/stacks/ezshare-go:latest
          imagePullPolicy: "Always"
          env:
            - name: DATA_DIR
              value: /data
          volumeMounts:
            - name: cpap-nfs
              mountPath: /data


