services:
  webhook-tester:
    image: ghcr.io/tarampampam/webhook-tester
    container_name: webhook-tester-up
    restart: unless-stopped
    command: --log-json serve --port 8080 --storage-driver redis --pubsub-driver redis --redis-dsn redis://webhook-tester-redis:6379/0
    depends_on:
      webhook-tester-redis: {condition: service_healthy}

    x-tailscale:
      upstream: http://webhook-tester-up:8080
      hostname: webhook-tester

    x-public-ingress:
      upstream: https://webhook-tester.tailnet-a578.ts.net
      hostname: hooks.keen.land

    x-web:
      upstream: https://webhook-tester.tailnet-a578.ts.net
      hostname: hooks
      require_auth: false

  webhook-tester-redis:
    container_name: webhook-tester-redis
    image: redis:7-alpine
    volumes: 
      - /data/webhook-tester/redis:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 1s
