services:
  ollama:
    container_name: ollama
    image: ollama/ollama
    volumes:
      - /data/ollama:/root/.ollama
    restart: unless-stopped
    x-web:
      port: 11434
      hostname: ollama
