---
apiVersion: v1
kind: Namespace
metadata:
  name: localllama
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ollama-pvc
  namespace: localllama
spec:
  storageClassName: longhorn-local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 120Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ollama
  namespace: localllama  
  labels:
    app: ollama
  annotations:
    keel.sh/policy: "major"
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@every 24h"
    keel.sh/approvals: "0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      nodeSelector:
        kubernetes.io/hostname: nibbler
      runtimeClassName: nvidia
      volumes:
        - name: ollama-data
          persistentVolumeClaim:
            claimName: ollama-pvc
      containers:
        - name: ollama
          image: ollama/ollama:0.11.3
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: ollama-data
              mountPath: /root/.ollama
          env:
            - name: NVIDIA_VISIBLE_DEVICES
              value: "all"
            - name: OLLAMA_KEEP_ALIVE
              value: "24h"
            - name: OLLAMA_FLASH_ATTENTION
              value: "1"
            - name: OLLAMA_KV_CACHE_TYPE
              value: "q8_0"
---
apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: localllama  
spec:
  selector:
    app: ollama
  ports:
    - protocol: TCP
      port: 11434
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ollama-private
  namespace: localllama  
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - ollama.keen.land
      secretName: keenland-ollama-ingress-cert
  rules:
    - host: ollama.keen.land
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ollama
                port:
                  number: 11434
