apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: litellm
  namespace: localllama
spec:
  instances: 2
  storage:
    storageClass: local-path
    size: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: litellm
  namespace: localllama
  labels:
    app: litellm
  annotations:
    keel.sh/policy: "force"
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@every 24h"
    keel.sh/approvals: "0"
    keel.sh/match-tag: "true"    
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: litellm
  template:
    metadata:
      labels:
        app: litellm
    spec:
      nodeSelector:
        topology.kubernetes.io/zone: home-1
      containers:
        - name: litellm
          image: ghcr.io/berriai/litellm-database:main-stable
          imagePullPolicy: "Always"
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: litellm-app
                  key: uri
            - name: LITELLM_MASTER_KEY
              value: sk-1234
            - name: STORE_MODEL_IN_DB
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: litellm
  namespace: localllama
spec:
  selector:
    app: litellm
  ports:
    - protocol: TCP
      port: 4000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: litellm-private
  namespace: localllama
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - litellm.keen.land
      secretName: keenland-litellm-ingress-cert
  rules:
    - host: litellm.keen.land
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: litellm
                port:
                  number: 4000
      
