defaults:
  stacks:
    - certificates
    - tailscale-auto
    - watchtower
  configs: []
  environment:
    - "TZ=America/Detroit"
    - "CONFIGS_DIR=/root/app/configs"

hosts:
  home:
    environment:
      - "CONFIG=/data/media"
      - "SCRATCH=/scratch"
      - "STATUS_PING_URL=https://status.keen.land/api/push/7KJGxFkmgM?status=up&msg=OK&ping="
      - "WATERFURNACE_DEVICE=tcp://100.77.179.116:20000"
    configs:
      - mosquitto
    stacks:
      - home-assistant
      - mqtt
      - tftp
      - docker-socket-proxy

  crushinator:
    configs:
      - scrutiny
    stacks:
      - scrutiny-crushinator

  nibbler:
    groups:
      - hypervisor
    environment:
      - "CONFIG=/data/media"
      - "SCRATCH=/vmpool/scratch"
    configs:
      - int-proxy
      - scrutiny
    stacks:
      - int-proxy
      - scrutiny-nibbler
      - file-browser

  docker01:
    environment:
      - "CONFIG=/data/media"
      - "SCRATCH=/scratch"
      - "SPEEDTEST_PORT=8910"
    configs:
      - unifi-cam-proxy
      - int-proxy
    stacks:
      - sabnzbd
      - calibre
      - media
      - speedtest
      - unifi-cam-proxy
      - paperless-ngx
      - spoolman
      - int-proxy
      - beancount
#      - icloud-photos
      - photoprism
      - ezshare
      - webhook-tester

  pkdn-host:
    environment:
      - "WATCHTOWER_POLL_INTERVAL=30"
    stacks:
      - pkdn
      - smolsrv

  proxy:
    configs:
      - int-proxy
      - ext-proxy
      - vouch-proxy
      - homer
    stacks:
      - int-proxy
      - ext-proxy
      - vouch-proxy
      - uptime-kuma
      - homer

  minecraft:
    stacks:
      - minecraft

  # shed zwave
  wyse-3040-9637:
    environment:
      - CONFIG=/data
    stacks:
      - zwave
      - genmon
    
  # office zwave
  wyse-3040-9835:
    environment:
      - "CONFIG=/data"
    stacks:
      - zwave
      - zigbee

  # garage zwave
  wyse-3040-9855:
    environment:
      - "CONFIG=/data"
    stacks:
      - zwave

  # house zwave
  wyse-3040-9c0d:
    environment:
      - "CONFIG=/data"
    stacks:
      - zwave
      - zigbee

  # waterfurnace
  wyse-3040-9588:
    environment:
      - "WATERFURNACE_DEVICE=/dev/rs485"
    groups:
      - ansible_deploy
    stacks:
      - waterfurnace
