defaults:
  stacks:
    - watchtower
    - common
    - ofelia
    - dozzle-agent
  environment:
    - "TZ=America/Detroit"
    - "CONFIGS_DIR=/root/app/stacks"
    - "CONFIG=/data"

hosts:
  hypnotoad-docker: # HP 800 G3 mini i7-7700T
    local_ip: 10.73.95.169
    stacks:
      - adsb-bubble
      - calendar-sync
      - calibre
      - coredns
      - ersatztv
      - ezshare-go
      - icloudpd-web
      - jellyfin
      - local-proxy
      - media
      - media-volume      
      - minecraft
      - stalwart
      - ultrafeeder
      - wyoming

  lrrr-docker: # VM running on the N150 box
    local_ip: 10.73.95.4
    stacks:
      - certificate-builder
      - coredns
      - dozzle
      - forgejo
      - forgejo-runner
      - gatus
      - genmon
      - home-assistant
      - homer
      - local-proxy
      - media-volume
      - mosquitto
      - omada-controller
      - paperless-ngx
      - parametric-zigbee
      - parametric-zwave
      - renovate
      - smtp-relay
      - waterfurnace
      - wg-easy

  ord2: # VM on Vultr
    local_ip: 149.28.117.193
    stacks:
      - ext-proxy
      - pkdn
      - smallsites
      - vmsave

  # rpi: # Raspberry Pi 4 by Pete's nightstand
  #   local_ip: 10.73.95.214
  #   stacks:
  #     - ezshare-proxy

  shed: # Dell Wyse 3040 in Shed
    local_ip: 10.73.95.223
    stacks:
      - ultrafeeder-feeder

  nibbler-docker-test:
    local_ip: 10.73.95.126
    stacks:
      - openwebui
      - ollama

