defaults:
  stacks:
    - watchtower
    - backup
    - common
    - ofelia
  environment:
    - "TZ=America/Detroit"
    - "CONFIGS_DIR=/root/app/stacks"
    - "CONFIG=/data"

hosts:
  hypnotoad-docker:
    stacks:
      - calendar-sync
      - calibre
      - ezshare-go
      - icloudpd-web
      - jellyfin
      - local-proxy
      - media
      - stalwart      

  lrrr-docker: # VM running on the N150 box
    stacks:
      - certificate-builder
      - gatus
      - genmon
      - home-assistant
      - homer
      - local-proxy
      - mosquitto
      - paperless-ngx
      - parametric-zigbee
      - parametric-zwave
      - sabnzbd
      - waterfurnace
      - wg-easy

  ord1: # VM on Vultr
    stacks:
      - ext-proxy
      - pkdn
      - smallsites
      - vmsave

  rpi: # Raspberry Pi 4 by Pete's nightstand
    stacks:
      - ezshare-proxy
