defaults:
  groups:
    - all
  stacks:
    - watchtower
    - common
    - ofelia
    - dozzle-agent
    - host-monitoring
  environment:
    - "TZ=America/Detroit"
    - "CONFIGS_DIR=/root/app/stacks"
    - "CONFIG=/data"

hosts:
  hermes: # Wyse 3040 in basement
    groups:
      - critical
    local_ip: 10.73.95.159
    stacks:
      - coredns

  hypnotoad-docker: # HP 800 G3 mini i7-7700T
    local_ip: 10.73.95.169
    groups:
      - production
    stacks:
      - adsb-bubble
      - caddy
      - calendar-sync
      - calibre
      - coredns
      - ersatztv
      - ezshare-go
      - icloudpd-web
      - local-proxies
      - jellyfin
      - media
      - media-volume
      - minecraft
      - stalwart
      - ultrafeeder
      - wyoming

  lrrr-docker: # VM running on the N150 box
    local_ip: 10.73.95.4
    groups:
      - critical
      - production
    stacks:
      - caddy
      - certificate-builder
      - coredns
      - dozzle
      - forgejo
      - forgejo-runner
      - gatus
      - genmon
      - home-assistant
      - homer
      - local-proxies
      - media-volume
      - mosquitto
      - omada-controller
      - paperless-ngx
      - parametric-zigbee
      - parametric-zwave
      - renovate
      - smtp-relay
      - waterfurnace
      - wg-easy

  ord2: # VM on Vultr
    local_ip: 149.28.117.193
    groups:
      - external-production
    stacks:
      - anubis
      - caddy
      - pkdn
      - smallsites
      - vmsave

  rpi: # Raspberry Pi 4 by Pete's nightstand
    local_ip: 10.73.95.214
    groups:
      - production
    stacks:
      - ezshare-proxy

  shed: # Dell Wyse 3040 in Shed
    local_ip: 10.73.95.223
    groups:
      - production
    stacks:
      - ultrafeeder-feeder

  hypnotoad-docker-test:
    local_ip: 10.73.95.218
    groups:
      - development
    stacks: []
      # - caddy
      # - anubis
      # - ext-proxies
