defaults:
  stacks:
    - watchtower
    - backup
    - common
  environment:
    - "TZ=America/Detroit"
    - "CONFIGS_DIR=/root/app/stacks"
    - "CONFIG=/data"

hosts:
  # hermes: # nee wyse-3040-9c0d
  #   environment:
  #     - "CONFIG=/data"
  #   stacks:
  #     - local-proxy
  #     - certificates

  hypnotoad-docker:
    environment:
      - "CONFIG=/data"
    stacks:
      - calendar-sync
      - calibre
      - certificates
      - ezshare-go
      - icloudpd-web
      - jellyfin
      - local-proxy
      - media
      - media-volume
      - smtp-relay
      - stalwart      

  lrrr-docker: # VM running on the N150 box
    environment:
      - "KEEPALIVED_INTERFACE=eth0"
    stacks:
      - certificates
      - gatus
      - genmon
      - home-assistant
      - homer
      - local-proxy
      - media-volume
      - mosquitto
      - paperless-ngx
      - parametric-zigbee
      - parametric-zwave
      - sabnzbd
      - smtp-relay
      - waterfurnace
      - wg-easy

  ord1: # VM on Vultr
    stacks:
      - ext-proxy
      - certificates
      - pkdn
      - smallsites
      - vmsave

  rpi: # Raspberry Pi 4 by Pete's nightstand
    stacks:
      - ezshare-proxy
