services:
  zigbee2mqtt:
    container_name: zigbeejs2mqtt
    hostname: zigbeejs2mqtt
    image: koenkk/zigbee2mqtt:latest
    restart: always
    stop_signal: SIGINT
    network_mode: host
    privileged: true
    volumes:
      - ${CONFIG}/zigbee:/app/data
      - /dev:/dev

