apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: smtp-relay-secrets
spec:
  itemPath: "vaults/fmycvdzmeyvbndk7s7pjyrebtq/items/fx57rmaxgc355ekvd7sa77emqy"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smtp-relay
  labels:
    app: smtp-relay
  annotations:
    keel.sh/policy: "major"
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@every 24h"
    keel.sh/approvals: "0"
    operator.1password.io/auto-restart: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smtp-relay
  template:
    metadata:
      labels:
        app: smtp-relay
    spec:
      imagePullSecrets:
        - name: ghcr.io
      containers:
        - name: smtp-relay
          image: djjudas21/smtp-relay:0.10.0
          imagePullPolicy: "IfNotPresent"
          envFrom:
            - secretRef:
                name: smtp-relay-secrets
          resources:
            requests:
              memory: '32Mi'
            limits:
              memory: '32Mi'
---
apiVersion: v1
kind: Service
metadata:
  name: smtp-relay
spec:
  selector:
    app: smtp-relay
  ports:
    - protocol: TCP
      port: 2525
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: smtp-relay
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       smtp-relay
  updatePolicy:
    updateMode: "Off"
