kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pocket-configs-pvc
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pocket
  labels:
    app: pocket
  annotations:
    keel.sh/policy: "major"
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@every 24h"
    keel.sh/approvals: "0"
    operator.1password.io/auto-restart: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pocket
  template:
    metadata:
      labels:
        app: pocket
    spec:
      volumes:
        - name: pocket-configs
          persistentVolumeClaim:
            claimName: pocket-configs-pvc
      containers:
        - name: pocket
          image: ghcr.io/pocket-id/pocket-id:v1.6.4
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: pocket-configs
              mountPath: /app/backend/data
          env:
            - name: PUBLIC_APP_URL
              value: https://pocket-id.keen.land
            - name: TRUST_PROXY
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: pocket
spec:
  selector:
    app: pocket
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pocket-private
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - pocket-id.keen.land
      secretName: keenland-pocket-ingress-cert
  rules:
    - host: pocket-id.keen.land
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pocket
                port:
                  number: 80
  
