apiVersion: onepassword.com/v1
kind: OnePasswordItem
type: kubernetes.io/dockerconfigjson
metadata:
  name: ghcr.io
  namespace: kube-system
spec:
  itemPath: "vaults/fmycvdzmeyvbndk7s7pjyrebtq/items/53gmfg3vpltilk2bcgn5i36hiq"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: dns-secrets
  namespace: kube-system
spec:
  itemPath: "vaults/fmycvdzmeyvbndk7s7pjyrebtq/items/umbys4jfnh6k27u2isqdimhz6i"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dns-updater
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dns-updater
rules:
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dns-updater
subjects:
- kind: ServiceAccount
  name: dns-updater
  namespace: kube-system
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: dns-updater
  apiGroup: ""    
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: dns-updater
  namespace: kube-system
spec:
  schedule: "*/30 * * * *"
  concurrencyPolicy: Forbid  
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 3600
      backoffLimit: 0
      template:
        spec:
          serviceAccountName: dns-updater
          restartPolicy: Never
          imagePullSecrets:
            - name: ghcr.io        
          containers:
            - name: dnscontrol
              image: ghcr.io/keenfamily-us/infra/dns:latest
              imagePullPolicy: "Always"
              resources:
                limits:
                  memory: "64Mi"
                requests:
                  memory: "64Mi"
              env:
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: dns-secrets
                      key: AWS_ACCESS_KEY_ID
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: dns-secrets
                      key: AWS_SECRET_ACCESS_KEY            
                - name: FLY_ACCESS_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: dns-secrets
                      key: FLY_ACCESS_TOKEN
