services:
  tftp-server:
    image: taskinen/tftp:latest
    entrypoint: in.tftpd
    command: -L -4 --secure --address 0.0.0.0:69 --verbosity 3 /var/tftpboot
    ports:
      - "0.0.0.0:69:69/udp"
    volumes:
      - /data/tftpboot:/var/tftpboot:ro
    restart: unless-stopped