kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: genmon-configs-pvc
  namespace: iot-system
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: genmon-logs-pvc
  namespace: iot-system
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: genmon
  namespace: iot-system
  labels:
    app: genmon
  annotations:
    keel.sh/policy: "force"
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@every 10m"
    keel.sh/approvals: "0"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: genmon
  template:
    metadata:
      labels:
        app: genmon
    spec:
      volumes:
        - name: genmon-configs
          persistentVolumeClaim:
            claimName: genmon-configs-pvc
        - name: genmon-logs
          persistentVolumeClaim:
            claimName: genmon-logs-pvc
        - name: devices
          hostPath:
            path: /dev
      containers:
        - name: genmon
          image: "ghcr.io/peterkeen/genmon-docker:main"
          imagePullPolicy: "Always"
          volumeMounts:
            - name: genmon-configs
              mountPath: /etc/genmon
            - name: genmon-logs
              mountPath: /var/log
            - name: devices
              mountPath: /dev
          resources:
            requests:
              memory: '128Mi'
            limits:
              memory: '128Mi'
        - name: genmon-proxy
          image: "ghcr.io/peterkeen/genmon-proxy:main"
          imagePullPolicy: "Always"
          command: ["/app/proxy"]
          args: ["--upstream", "http://localhost:8000"]
          resources:
            requests:
              memory: '16Mi'
            limits:
              memory: '16Mi'          
---
apiVersion: v1
kind: Service
metadata:
  name: genmon
  namespace: iot-system
spec:
  selector:
    app: genmon
  ports:
    - protocol: TCP
      port: 8000
      name: web
    - protocol: TCP
      port: 80
      name: proxy
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: genmon-private
  namespace: iot-system
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - genmon.keen.land
        - genmon-proxy.keen.land
      secretName: keenland-genmon-ingress-cert
  rules:
    - host: genmon.keen.land
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: genmon
                port:
                  number: 8000
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: genmon
  namespace: iot-system
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       genmon
  updatePolicy:
    updateMode: "Off" 
