apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: smartbed-secrets
spec:
  itemPath: "vaults/fmycvdzmeyvbndk7s7pjyrebtq/items/oqhirfypovxukgcmsml6c6m3hu"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: smartbed-config
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartbed
  labels:
    app: smartbed
  annotations:
    keel.sh/policy: "force"
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@every 24h"
    keel.sh/approvals: "0"
    keel.sh/match-tag: "true"
    operator.1password.io/auto-restart: "true"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: smartbed
  template:
    metadata:
      labels:
        app: smartbed
    spec:
      terminationGracePeriodSeconds: 1
      containers:
        - name: smartbed
          image: ghcr.io/richardhopton/smartbed-mqtt:main
          imagePullPolicy: "Always"
          envFrom:
            - secretRef:
                name: smartbed-secrets
          volumeMounts:
            - name: smartbed-config
              mountPath: /data
        - name: smartbed-shell
          image: alpine:3
          imagePullPolicy: "Always"
          volumeMounts:
            - name: smartbed-config
              mountPath: /data
          command: ["sh", "-c", "tail -f /dev/null"]                                          
      imagePullSecrets:
        - name: ghcr.io
      volumes:
        - name: smartbed-config
          persistentVolumeClaim:
            claimName: smartbed-config
