kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: paperless-configs-pvc
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: paperless-redis-pvc
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paperless
  labels:
    app: paperless
  annotations:
    keel.sh/policy: "major"
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@every 24h"
    keel.sh/approvals: "0"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: paperless
  template:
    metadata:
      labels:
        app: paperless
    spec:
      nodeSelector:
        topology.kubernetes.io/zone: home-1
      volumes:
        - name: documents-nfs
          nfs:
            server: 10.73.95.84
            path: /mnt/tank/documents
        - name: consume-nfs
          nfs:
            server: 10.73.95.84
            path: /mnt/tank/documents/consume
        - name: export-nfs
          nfs:
            server: 10.73.95.84
            path: /mnt/tank/documents/export
        - name: paperless-configs
          persistentVolumeClaim:
            claimName: paperless-configs-pvc
        - name: paperless-redis
          persistentVolumeClaim:
            claimName: paperless-redis-pvc
      containers:
        - name: paperless-ngx-webserver
          image: ghcr.io/paperless-ngx/paperless-ngx:2.17.1
          imagePullPolicy: "IfNotPresent"
          env:
            - name: PAPERLESS_REDIS
              value: redis://localhost:6379
            - name: PAPERLESS_TIME_ZONE
              value: America/Detroit
            - name: PAPERLESS_URL
              value: https://docs.keen.land
            - name: PAPERLESS_ALLOWED_HOSTS
              value: docs.keen.land,localhost:8000
            - name: PAPERLESS_CSRF_TRUSTED_ORIGINS
              value: https://docs.keen.land
            - name: PAPERLESS_OCR_USER_ARGS
              value: '{"invalidate_digital_signatures": true}"'
            - name: DEBUG
              value: "True"
            - name: GRANIAN_PORT
              value: "8000"
          volumeMounts:
            - name: documents-nfs
              mountPath: /usr/src/paperless/media
            - name: consume-nfs
              mountPath: /usr/src/paperless/consume
            - name: export-nfs
              mountPath: /usr/src/paperless/export
            - name: paperless-configs
              mountPath: /usr/src/paperless/data
        - name: paperless-ngx-broker
          image: redis:8
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: paperless-redis
              mountPath: /data
---
apiVersion: v1
kind: Service
metadata:
  name: paperless
spec:
  selector:
    app: paperless
  ports:
    - protocol: TCP
      port: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: paperless-private
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - docs.keen.land
      secretName: keenland-paperless-ingress-cert
  rules:
    - host: docs.keen.land
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: paperless
                port:
                  number: 8000
