apiVersion: v1
kind: Pod
metadata:
  name: jellyfin-sync
spec:
  volumes:
    - name: media-nfs
      nfs:
        server: 10.73.95.84
        path: /mnt/tank/media
    - name: jellyfin-config
      persistentVolumeClaim:
        claimName: jellyfin-configs-pvc
    - name: jellyfin-cache
      nfs:
        server: 10.73.95.84
        path: /mnt/tank/media/jellyfin/cache
  containers:
    - name: sync
      image: ubuntu:latest
      stdin: true
      imagePullPolicy: "Always"
      securityContext:
        privileged: true
        runAsUser: 0
      volumeMounts:
        - name: media-nfs
          mountPath: /mnt/media
        - name: jellyfin-config
          mountPath: /config
          readOnly: true
        - name: jellyfin-cache
          mountPath: /cache
          readOnly: true
