apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mistral-7b
  namespace: localllama
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi
  storageClassName: longhorn-local
  volumeMode: Filesystem
