apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: hugging-face-public-read-token
  namespace: localllama
spec:
  itemPath: "vaults/fmycvdzmeyvbndk7s7pjyrebtq/items/hu7g2iqbcb4ycoo6uru6epbvu4"
