---
apiVersion: v1
kind: Namespace
metadata:
  name: forgejo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forgejo-pvc
  namespace: forgejo
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: forgejo
  namespace: forgejo
  labels:
    app: forgejo
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: forgejo
  template:
    metadata:
      labels:
        app: forgejo
    spec:
      nodeSelector:
        topology.kubernetes.io/zone: home-1      
      volumes:
        - name: forgejo
          persistentVolumeClaim:
            claimName: forgejo-pvc
      containers:
        - name: forgejo
          image: codeberg.org/forgejo/forgejo:11.0
          imagePullPolicy: "Always"
          volumeMounts:
            - name: forgejo
              mountPath: /data
          env:
            - name: "USER_UID"
              value: "1000"
            - name: "USER_GID"
              value: "1000"
---
apiVersion: v1
kind: Service
metadata:
  name: forgejo
  namespace: forgejo  
spec:
  selector:
    app: forgejo
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: web
    - protocol: TCP
      port: 22
      targetPort: 22
      name: ssh
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: forgejo-private
  namespace: forgejo  
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - git.keen.land
      secretName: keenland-git-ingress-cert
  rules:
    - host: git.keen.land
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: forgejo
                port:
                  number: 3000

