services:
  forgejo:
    image: codeberg.org/forgejo/forgejo:9
    container_name: forgejo-up
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    volumes:
      - /tank/code:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    x-tailscale:
      hostname: forgejo
      upstream: http://forgejo-up:3000

