services:
  certificate-builder:
    image: goacme/lego
    container_name: certificate-builder
    environment:
      - CONFIGS_SHA
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION=us-east-1
      - GATUS_API_TOKEN
    volumes:
      - /data/certificates:/certificates
      - ${CONFIGS_DIR}/certificate-builder/generate.sh:/generate.sh
      - ${CONFIGS_DIR}/certificate-builder/entrypoint.sh:/entrypoint.sh
      - ${CONFIGS_DIR}/certificate-builder/certs.txt:/certs.txt
    entrypoint: "/bin/ash"
    command: ["/entrypoint.sh"]
    restart: unless-stopped
    x-cron:
      - name: "generate certificates"
        schedule: "10 13 23 * * *"
        command: "/bin/ash /generate.sh"
    x-op-items:
      - n6zq3ryqxlvminvgt55bkmn3vi
    x-backup:
      paths:
        - /data/certificates
