apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: adsb-bubble-secrets
spec:
  itemPath: "vaults/fmycvdzmeyvbndk7s7pjyrebtq/items/33cvpfteyuy7mjcprlqsiejeeq"
---  
apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/tailnet-fqdn: "ultrafeeder.tailnet-a578.ts.net"
  name: ultrafeeder-ts   # service name
spec:
  externalName: ultrafeeder   # any value - will be overwritten by operator
  type: ExternalName
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adsb-bubble
  labels:
    app: adsb-bubble
  annotations:
    keel.sh/policy: "force"
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@every 1m"
    keel.sh/approvals: "0"
    operator.1password.io/auto-restart: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adsb-bubble
  template:
    metadata:
      labels:
        app: adsb-bubble
    spec:
      volumes:
        - name: secrets
          secret:
            secretName: adsb-bubble-secrets
      imagePullSecrets:
        - name: ghcr.io
      containers:
        - name: adsb-bubble
          image: ghcr.io/keenfamily-us/infra/stacks/adsb-bubble:latest
          imagePullPolicy: "Always"
          resources:
            requests:
              memory: 64Mi
            limits:
              memory: 64Mi
          volumeMounts:
            - name: secrets
              mountPath: /secrets
              readOnly: true          
          env:
            - name: HASS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: adsb-bubble-secrets
                  key: HASS_API_KEY
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: adsb-bubble
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       adsb-bubble
  updatePolicy:
    updateMode: "Off"
