services:
  jellyfin:
    container_name: jellyfin-up
    hostname: jellyfin
    image: ghcr.io/jellyfin/jellyfin:10.10.7
    user: 1000:1000
    group_add:
      - "27"
    volumes:
      - media-nfs:/mnt/media:ro
      - /data/jellyfin:/config
      - jellyfin-cache:/cache
      - /scratch/jellyfin:/transcodes
      - ${CONFIGS_DIR}/jellyfin/clean_cache.sh:/clean_cache.sh
    restart: unless-stopped
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/${CARD_NAME:-card0}:/dev/dri/${CARD_NAME:-card0}
    x-web:
      port: 8096
      dashboard:
        name: Jellyfin
        subtitle: Watch our media
        category: Media and Games
        sort_order: 1
    x-cron:
      - name: "clean jellyfin cache"
        schedule: "0 */15 * * * *"
        command: "/clean_cache.sh"
    x-backup:
      paths:
        - /data/jellyfin

volumes:
  jellyfin-cache: {}
