services:
  sabnzbd:
    container_name: sabnzbd-up
    image: lscr.io/linuxserver/sabnzbd:latest
    hostname: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Detroit
    volumes:
      - ${CONFIG}/sabnzbd:/config
      - media-nfs:/downloads
      - sabnzbd-scratch:/incomplete-downloads
      - cwa-book-ingest:/cwa-book-ingest
    restart: unless-stopped
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    x-web:
      port: 8080
    x-backup:
      paths:
        - /data/sabnzbd

volumes:
  sabnzbd-scratch:

x-depends:
  - media-volume
