services:
  dozzle:
    container_name: dozzle-up
    hostname: logs
    image: amir20/dozzle:latest
    restart: always
    environment:
      - "DOZZLE_ENABLE_ACTIONS=true"
      - "DOZZLE_REMOTE_AGENT=#<Host:0x000000010541b030>.tailnet-a578.ts.net:7007,#<Host:0x00000001080793e8>.tailnet-a578.ts.net:7007,#<Host:0x00000001080755b8>.tailnet-a578.ts.net:7007,#<Host:0x00000001080726d8>.tailnet-a578.ts.net:7007"
    x-tailscale:
      hostname: dozzle
      upstream: http://dozzle-up:8080
