services:
  u2if:
    container_name: u2if
    build: .
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment:
      - CONFIGS_SHA
    volumes:
      - /dev:/dev
      - /data/u2if/script.py:/app/script.py
