services:
  forgejo:
    image: codeberg.org/forgejo/forgejo:1.21
    container_name: forgejo
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    volumes:
      - /tank/code:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    network_mode: service:forgejo-ts

  forgejo-ts:
    image: ghcr.io/boinkor-net/tsnsrv:latest
    container_name: forgejo-ts
    hostname: forgejo
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_AUTHKEY
    volumes:
      - "/data/ts/forgejo-ts:/var/lib/tailscale"
    command: ["-name", "forgejo", "http://127.0.0.1:3000"]
