services:
  glances:
    image: nicolargo/glances:latest-full
    container_name: glances
    ports:
      - "$TAILNET_IP:61208:61208"
    volumes:
      - $CONFIGS_DIR/glances/glances.conf:/glances/conf/glances.conf
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    pid: host
