services:
  pete-icloud-photos:
    user: 1000:1000
    image: icloudpd/icloudpd:latest
    container_name: pete-icloud-photos
    environment:
      - TZ
    volumes:
      - /tank/photos/pete:/data
    command: [ "icloudpd", "--directory", "/data", "--username", "${PETE_ICLOUD_PHOTO_EMAIL}", "--password", "${PETE_ICLOUD_PHOTO_PASSWORD}", "--cookie-directory", "/data", "--watch-with-interval", "3600"]

  emily-icloud-photos:
    user: 1000:1000
    image: icloudpd/icloudpd:latest
    container_name: emily-icloud-photos
    environment:
      - TZ
    volumes:
      - /tank/photos/emily:/data
    command: [ "icloudpd", "--directory", "/data", "--username", "#{EMILY_ICLOUD_PHOTO_EMAIL}", "--password", "${EMILY_ICLOUD_PHOTO_PASSWORD}", "--cookie-directory", "/data", "--watch-with-interval", "3600"]
