services:
  kopia:
    image: kopia/kopia:latest
    container_name: kopia-up
    command:
      - server
      - start
      - --disable-csrf-token-checks
      - --insecure
      - --address=0.0.0.0:51515
      - --server-username=admin
      - --server-password=admin
    restart: unless-stopped
    environment:
      - KOPIA_PASSWORD=${KOPIA_REPOSITORY_PASSWORD}
      - USER=${KOPIA_REPOSITORY_USERNAME}
    volumes:
      # Mount local folders needed by kopia
      - /data/kopia/config:/app/config
      - /scratch/kopia:/app/cache
      - /data/kopia/logs:/app/logs
      # Mount local folders to snapshot
      - /data:/data:ro
      # Mount repository location
      - /tank/backups/kopia:/repository
    x-tailscale:
      upstream: http://kopia-up:51515
      hostname: kopia
