services:
  netdata:
    image: netdata/netdata:stable
    container_name: netdata
    hostname: home.local
    ports:
      - 19999:19999
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /data/netdata/config:/etc/netdata
      - /data/netdata/lib:/var/lib/netdata
      - /data/netdata/cache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/run/docker.sock:/var/run/docker.sock
    x-dashy:
      title: 'Netdata'
      http_port: 19999
      section: Network
