services:
  nexus:
    container_name: nexus
    image: sonatype/nexus3
    restart: always
    networks:
      - tailnet
    ports:
      - '8081:8081'
      - '8082:8082'
    volumes:
      - nexus-data:/nexus-data
networks:
  tailnet:
    external: true
volumes:
  nexus-data:
    name: nexus-data

