version: '3.8'

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui-up
    volumes:
      - /data/open-web-ui:/app/backend/data
    environment:
      - 'OLLAMA_BASE_URL=http://nibbler.tailnet-a578.ts.net:11434'
    restart: unless-stopped
    x-tailscale:
      upstream: http://open-webui-up:8080
      hostname: ollama-web
