services:
   speedtest:
     environment:
       - "PORT=${SPEEDTEST_PORT:-8080}"
     container_name: speedtest
     image: ghcr.io/keenfamily-us/speedtest-api:master
     network_mode: host
     restart: unless-stopped
