services:
  tailscale:
    hostname: tailscale
    image: tailscale/tailscale:stable
    environment:
      - TAILSCALE_AUTH_KEY
      - TAILSCALE_HOSTNAME
      - TAILSCALE_STATE_ARG=/var/lib/tailscale_state/tailscale.state
      - CONFIGS_SHA
    volumes:
      - /var/lib/tailscale_state/
      - ${CONFIGS_DIR}/tailscale-test/start.sh:/start.sh
    command: ["/start.sh"]
    ports:
      - "8888:80"

  nginx-hello:
    image: nginxdemos/hello
    network_mode: "service:tailscale"
    depends_on:
      - tailscale
