services:
  uptime-kuma:
    container_name: uptime-kuma
    hostname: status
    image: kfcr.fly.dev/louislam/uptime-kuma:1-alpine
    environment:
      - UPTIME_KUMA_DISABLE_FRAME_SAMEORIGIN=true
    ports:
      - "${TAILNET_IP}:3001:3001"
    volumes:
      - /data/uptime-kuma:/app/data
    restart: always
    x-web:
      require_auth: false
      port: 3001
