kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: calibre-configs-pvc
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: calibre
spec:
  selector:
    app: calibre
  ports:
    - protocol: TCP
      port: 8083
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: calibre-private
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - books.keen.land
      secretName: keenland-calibre-ingress-cert
  rules:
    - host: books.keen.land
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: calibre
                port:
                  number: 8083
---                  
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: calibre
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       calibre
  updatePolicy:
    updateMode: "Off" 
