services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    hostname: open-webui
    container_name: open-webui
    volumes:
      - /data/open-webui:/app/backend/data
    restart: unless-stopped
    x-web:
      port: 8080

