services:
  smolsrv:
    image: ghcr.io/peterkeen/smolsrv:main
    container_name: smolsrv-up
    restart: unless-stopped
    environment:
      - RACK_ENV=production
      - SMOLSRV_DATA_PATH=/data
      - SMOLSRV_DISTRIBUTION_LIST=peter.keen@gmail.com
      - SMOLSRV_MESSAGE_ID_DOMAIN=smol.keenfamily.us
      - SMOLSRV_WEBHOOK_KEY
      - FORWARDEMAIL_API_TOKEN
    volumes:
      - /data/smolsrv:/data

    x-tailscale:
      hostname: smolsrv
      upstream: http://smolsrv-up:9292

    x-public-ingress:
      upstream: https://smolsrv.tailnet-a578.ts.net:443
      hostname: smol.keenfamily.us
