services:
  ipex-llm:
    container_name: ipex-llm-up
    image: intelanalytics/ipex-llm-inference-cpp-xpu:latest
    privileged: true
    command: ["/app/start-ollama.sh"]    
    environment:
      - OLLAMA_INTEL_GPU=true
      - OLLAMA_HOST=0.0.0.0
    ports:
      - 11444:11434
    volumes:
      - .:/app
      - /data/ipex-llm:/models
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped

