services:
  whisper:
    container_name: whisper-up
    image: rhasspy/wyoming-whisper
    volumes:
      - /data/whisper-piper:/data
    command: ["--model", "tiny-int8", "--language", "en"]
    restart: unless-stopped
    ports:
      - "${TAILNET_IP}:10300:10300"

  piper:
    container_name: piper-up
    image: rhasspy/wyoming-piper
    volumes:
      - /data/whisper-piper:/data
    command: ["--voice", "en_US-lessac-medium"]
    restart: unless-stopped
    ports:
      - "${TAILNET_IP}:10200:10200"


  openwakeword:
    container_name: openwakeword-up
    image: rhasspy/wyoming-openwakeword
    command: ["--preload-model", "ok_nabu"]
    restart: unless-stopped
    ports:
      - "${TAILNET_IP}:10400:10400"
