kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: piper-pvc
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: piper
  labels:
    app: piper
  annotations:
    keel.sh/policy: "major"
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@every 24h"
    keel.sh/approvals: "0"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: piper
  template:
    metadata:
      labels:
        app: piper
    spec:
      nodeSelector:
        topology.kubernetes.io/zone: home-1
      volumes:
        - name: piper-data
          persistentVolumeClaim:
            claimName: piper-pvc
      containers:
        - name: piper
          image: rhasspy/wyoming-piper:1.6.3
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: piper-data
              mountPath: /data
          args: ["--voice", "en_US-lessac-medium"]
---
apiVersion: v1
kind: Service
metadata:
  name: piper
spec:
  selector:
    app: piper
  ports:
    - protocol: TCP
      port: 10200
