kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: whisper-pvc
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whisper
  labels:
    app: whisper
  annotations:
    keel.sh/policy: "major"
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@every 24h"
    keel.sh/approvals: "0"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: whisper
  template:
    metadata:
      labels:
        app: whisper
    spec:
      nodeSelector:
        kubernetes.io/hostname: nibbler
      runtimeClassName: nvidia
      volumes:
        - name: whisper-data
          persistentVolumeClaim:
            claimName: whisper-pvc
      containers:
        - name: whisper
          image: lscr.io/linuxserver/faster-whisper:2.5.0
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: whisper-data
              mountPath: /data
          env:
            - name: WHISPER_MODEL
              value: Systran/faster-distil-whisper-small.en
            - name: WHISPER_LANG
              value: en
---
apiVersion: v1
kind: Service
metadata:
  name: whisper
spec:
  selector:
    app: whisper
  ports:
    - protocol: TCP
      port: 10300
