- name: Chrony
  hosts: all
  tasks:
    - name: Install Chrony
      ansible.builtin.package:
        name: chrony
        state: present

    - name: Install gpsd
      ansible.builtin.package:
        name: gpsd
        state: present
      when: "'lrrr' in inventory_hostname"

    - name: Enable gpsd
      ansible.builtin.service:
        name: gpsd
        state: started
        enabled: yes
      when: "'lrrr' in inventory_hostname"

    - name: Copy stratum0 conf
      ansible.builtin.copy:
        src: files/chrony/chrony.stratum0.conf
        dest: /etc/chrony/chrony.conf
        backup: yes
      when: "'lrrr' in inventory_hostname"        
      notify:
        - restart chronyd

    - name: Copy default conf
      ansible.builtin.copy:
        src: files/chrony/chrony.conf
        dest: /etc/chrony/chrony.conf
        backup: yes
      when: "'lrrr' not in inventory_hostname"
      notify:
        - restart chronyd

  handlers:
    - name: restart chronyd
      ansible.builtin.service:
        name: chronyd
        state: restarted
        enabled: yes
