- name: Serials Firewall
  hosts: serial
  tasks:
    - name: Install awall
      ansible.builtin.package:
        name: awall
        state: present

    - name: Copy firewall rules
      ansible.builtin.copy:
        src: firewall/optional/serials.json
        dest: /etc/awall/optional/

    - name: Enable firewall rules
      community.general.awall:
        name: serials
        state: enabled
        activate: true
