- name: Serials
  hosts: serial
  tasks:
    - name: Remove ser2net
      ansible.builtin.package:
        name: ser2net
        state: absent

    - name: Install eudev
      ansible.builtin.package:
        name:
          - eudev
          - udev-init-scripts
        state: present

    - name: Add eudev rules
      ansible.builtin.copy:
        src: "eudev/99-usb-serial.rules"
        dest: /etc/udev/rules.d/99-usb-serial.rules

    - name: udev service
      ansible.builtin.service:
        name: udev
        state: started
        enabled: yes

    - name: udev-trigger service
      ansible.builtin.service:
        name: udev-trigger
        state: started
        enabled: yes

    - name: udev-settle service
      ansible.builtin.service:
        name: udev-settle
        state: started
        enabled: yes

    - name: udev-postmount service
      ansible.builtin.service:
        name: udev-postmount
        state: started
        enabled: yes
