services:
  vector:
    container_name: vector
    image: timberio/vector:0.44.0-debian
    environment:
      - CONFIGS_SHA
      - HOSTNAME
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${CONFIGS_DIR}/vector/vector.yaml:/etc/vector/vector.yaml:ro
