version: "3"

services:
  dns-server:
    container_name: dns-server
    hostname: dns-server
    image: kfcr.fly.dev/technitium/dns-server:11.5.2
    network_mode: "host"
    environment:
      - HOSTNAME
      - DNS_SERVER_DOMAIN=dns-server
    volumes:
      - /data/dns:/etc/dns
    restart: unless-stopped
