- name: Stacks
  hosts: 
    - stacked
  tasks:
    - name: Install rsync
      ansible.builtin.package:
        name: rsync
        state: present

    - name: Copy conf
      ansible.posix.synchronize:
        src: "build/{{ inventory_hostname }}/"
        dest: /root/app/
        
    - name: Start stack
      ansible.builtin.shell: docker compose up --detach --quiet-pull --no-color
      args:
        chdir: /root/app
        
