kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mosquitto
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  labels:
    app: mosquitto
  annotations:
    keel.sh/policy: "major"
    keel.sh/trigger: "poll"
    keel.sh/pollSchedule: "@every 24h"
    keel.sh/approvals: "1"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
      annotations:
    spec:
      nodeSelector:
        topology.kubernetes.io/zone: home-1
      volumes:
        - name: mosquitto
          persistentVolumeClaim:
            claimName: mosquitto
        - name: mosquitto-config
          configMap:
            name: mosquitto
      containers:
        - name: mosquitto
          image: eclipse-mosquitto:2.0.22
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: mosquitto
              mountPath: /mosquitto
          env:
            - name: TZ
              value: America/Detroit
          resources:
            requests:
              memory: '128Mi'
            limits:
              memory: '128Mi'
---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto
spec:
  clusterIP: None
  selector:
    app: mosquitto
  ports:
    - protocol: TCP
      port: 1883
      targetPort: 1883
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: mosquitto
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       mosquitto
  updatePolicy:
    updateMode: "Off" 
